### ISSUE TITLE
Adding slider

### ISSUE THREAD

**Issue by smartdreams** [anarion80/gatsby-ghost-simply#4]
Hi, 

Very nice theme. How do I add the slider like you did in https://gatsby-ghost-simply.netlify.app/index-photographer ?
Is that something Ghost already provided?

Thank you.

**Comment by anarion80** [comment]
Hi, this is from the theme - Portfolio page as described in the original theme: https://godofredo.ninja/ghost-theme/simply/portfolio/

But no need to create portfolio page as in the original - just use internal tags on the post.

**Comment by smartdreams** [comment]
Thank you!
